name: Test CI for Go optimizations course

on: [ push ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    steps:
      - uses: actions/checkout@v4
      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.2'
          cache-dependency-path: homeworks/hw1/go.sum
      - name: dependencies
        working-directory: ./homeworks/hw1
        run: go mod tidy
      - name: test
        working-directory: ./homeworks/hw1
        run: go test -v ./...
#      - name: test artifacts
#        uses: actions/upload-artifact@v4
#        with:
#          name: results
#          path: ./homeworks/hw2 // TODO
